draios/instruqt-assets

falco101/falco-assessment/Dockerfile, falco101/falco-assessment/DockerfileJoedoe, falco101/falco-assessment/deployment-joe.yaml
=> [falco-assessment] new approach for user

falco101/falco-assessment/Dockerfile
=> [falco-assessment] new approach for user 2

common/prepare-track/init.sh, common/prepare-track/install_with_helm.sh
- cleans up helm tests.
- increases helm test timeout to 2 minutes
- invokes clean_setup at the end of the setup function
The script is still not testing docker and host.
=> Helm test improvements and enables clean_setup

common/prepare-track/init.sh
- Fixed region selection that wouldn't work as intended for US West.
- Changed error messages to better explain the issue.
=> Fix Region selection bug

common/prepare-track/init.sh
Code needs a space after the quotes at the end of the line.
https://sysdigcloud.slack.com/archives/GPW3T4T7V/p1639504464006900
=> Fix error with wrong collector

common/prepare-track/init.sh
=> [assets] nginx patch fix

common/prepare-track/init.sh
=> [init.sh] inscrease time and improve readibility

common/prepare-track/init.sh, common/prepare-track/install_with_docker.sh, common/prepare-track/install_with_helm.sh, common/prepare-track/install_with_host.sh
- adds logs to install_with_*
- adds docker case to test_agent
- runs the final install command in the background
=> [prepare-track] Test docker agent and add logs to install_with

common/sysdig-agent/values.yaml
=> [common] services not detected by agent

common/prepare-track/init.sh
=> [suggestion] keep nginx

common/prepare-track/init.sh
init.sh not working as expected for instruqt track test
=> check user for track test

common/prepare-track/init.sh
Revert "check user for track test"
This reverts commit 0648461152f7182bde3679362c75dbe15e3dd555.
=> Revert suggested changes.

common/prepare-track/install_with_helm.sh, common/sysdig-agent/values.yaml
Add parameter to capture metadata in k3s containerd clusters
Closes draios/instruqt#200
=> Add parameter to capture metadata in k3s

monitor/prometheus-extends-sysdig-forecast/allocateMem.sh
Add a wait so the allocation script starts when the agent is already monitoring the host
=> [prometheus-extends-sysdig-forecast] update allocate script

common/prepare-track/init.sh, common/sysdig-agent/values.yaml
This PR proposes the change of the default behavior (no parameters). Instead of installing everything, we don't install anything.
=> [prepare-track] if no params, set region only

cloud/fargate/cloudformation/network.tf, cloud/fargate/cloudformation/orchestrator.yaml, cloud/fargate/cloudformation/task_template.yaml, cloud/fargate/terraform/instrumented_load.tf, cloud/fargate/terraform/load.tf, cloud/fargate/terraform/main.tf, cloud/fargate/terraform/network.tf, cloud/fargate/terraform/orchestrator.tf, cloud/fargate/terraform/variables.tf
=> [aws-fargate] tf and cf assets

workshops/a-practical-guide-to-customizing-falco/Dockerfile, workshops/a-practical-guide-to-customizing-falco/vulnerable-app.yaml
Creates the assets used in challenge 3 of the customizing falco workshop
=> [workshop-falco-customizing] ch3 assets

common/prepare-track/init.sh, common/prepare-track/install_with_helm.sh
* persist user api endpoints
*  add kspm helm option
* add option to skip cleanup of setup files
=> [init.sh] multiple changes

common/prepare-track/cloud/install_with_terraform.sh, common/prepare-track/init.sh, common/prepare-track/install_with_helm.sh
Multiple changes to update how we deploy the agent with Helm:
* Update to new chart
* Update chart parameter to use new fields based on map [here](https://github.com/sysdiglabs/charts/blob/master/charts/sysdig-deploy/scripts/migrate_values.py)
* remove `USE_NODE_IMAGE_ANALYZER`
* Change regions logic and naming to be aligned with docs
TODO: check `agent.auditLog.auditServerUrl` and `agent.auditLog.auditServerPort` for our envs
=> [instruqt] helm chart upgrade

common/prepare-track/init.sh
helper branch to debug automation tests for monitoring-integrations PR: draios/instruqt#463
=> [init.sh] debug + logic improvements

common/prepare-track/account-provisioner-user-create.sh
add custom param to set region id
=> [account-provisioner] region id

common/prepare-track/account-provisioner-user-create.sh, common/prepare-track/init.sh, common/prepare-track/lab_random_string_id.sh
* change randomize string with dictionary for user + cluster names
* add user monitor operations team
=> User account-provisioner upgrades

common/prepare-track/install_with_helm.sh
Reason: https://sysdigcloud.slack.com/archives/C02ESJ5KH0X/p1683760716278619?thread_ts=1683760095.584789&cid=C02ESJ5KH0X
=> [init.sh] add drift_control detection

common/prepare-track/create_sysdig_user_and_team_scope.py
add namespace filter to team scoping
=> add namespace to python script

common/prepare-track/cloud/install_with_terraform.sh
if integration with specific existing AWS account exist, onboarding script was failing. This PR is to be able to handle this problem.
=> fix aws agentless onboarding
